disable-version-string: true
with-expecter: true
inpackage: true
dir: "{{.InterfaceDir}}"
mockname: "mock{{.InterfaceName|firstUpper}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}_test.go"
all: true
packages:
  github.com/ministryofjustice/opg-data-lpa-uid/lambda/create-case:
