all: true
dir: '{{.InterfaceDir}}'
structname: mock{{.InterfaceName|firstUpper}}
pkgname: '{{.SrcPackageName}}'
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/ministryofjustice/opg-data-lpa-uid/internal/event: {}
  github.com/ministryofjustice/opg-data-lpa-uid/lambda/create-case: {}
