---
version: "3.6"

services:
  lambda-create-case:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/lpa-id:latest
    build:
      context: ./lambda/create-case
      dockerfile: ../Dockerfile
    environment:
      AWS_REGION: eu-west-1
      AWS_S3_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
    volumes:
      - "./lambda/.aws-lambda-rie:/aws-lambda"
    entrypoint: /aws-lambda/aws-lambda-rie /var/task/main

  delegator:
    depends_on: [lambda-create-case]
    build:
      context: ./lambda/delegator
      dockerfile: ../Dockerfile
    entrypoint: /var/task/main
    ports:
      - "8080:8080"

  localstack:
    image: localstack/localstack:1.4
    depends_on: [delegator]
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DEFAULT_REGION: eu-west-1
      LAMBDA_FORWARD_URL: http://delegator:8080
      DOCKER_HOST: unix:///var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:4566 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
