---
version: "3.6"

services:
  lambda-create-case:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/integrations/lpa-uid-create-case-lambda:latest
    build:
      context: ./lambda/create-case
      dockerfile: ../Dockerfile
    environment:
      AWS_REGION: eu-west-1
      AWS_DYNAMODB_ENDPOINT: http://localstack:4566
      AWS_DYNAMODB_TABLE_NAME: lpa-uid-local
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
    volumes:
      - "./lambda/.aws-lambda-rie:/aws-lambda"
    entrypoint: /aws-lambda/aws-lambda-rie /var/task/main

  delegator:
    image: delegator
    depends_on: [lambda-create-case]
    build:
      context: ./delegator
      dockerfile: ../lambda/Dockerfile
    entrypoint: /var/task/main

  localstack:
    image: localstack/localstack:1.4
    depends_on: [delegator]
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - "lpa-uid.execute-api.localhost.localstack.cloud"
    environment:
      LAMBDA_FORWARD_URL: http://delegator:8080
      DOCKER_HOST: unix:///var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:4566 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

  pact-verifier:
    image: pactfoundation/pact-ref-verifier
    entrypoint:
      - pact_verifier_cli
      - --hostname=lpa-uid.execute-api.localhost.localstack.cloud
      - --port=4566
      - --base-path=/current/
      - --broker-url=https://pact-broker.api.opg.service.justice.gov.uk/
      - --provider-name=data-lpa-uid
