graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [opg-data-lpa-id - App - Components]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 4 [App]
      style 4 fill:#ffffff,stroke:#444444,color:#444444

      5("<div style='font-weight: bold'>API Gateway</div><div style='font-size: 70%; margin-top: 0px'>[Component: AWS API Gateway]</div><div style='font-size: 80%; margin-top:10px'>TBC</div>")
      style 5 fill:#85bbf0,stroke:#5d82a8,color:#000000
      6("<div style='font-weight: bold'>Generate New ID</div><div style='font-size: 70%; margin-top: 0px'>[Component: AWS Lambda, Go]</div><div style='font-size: 80%; margin-top:10px'>TBC</div>")
      style 6 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

    5-. "<div>Communicates with</div><div style='font-size: 70%'></div>" .->6
  end