name: "Build Images"

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    secrets:
      github_access_token:
        description: "Github Token"
        required: true
      snyk_token:
        description: "Snyk Token"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: "0"
      - name: Image cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: /tmp/images
          key: ${{ runner.os }}-images-${{ github.run_id }}-${{ github.run_number }}

      - name: Build Images
        run: make build

      - name: Debug
        run: docker image ls

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_MANAGEMENT_ECR_ROLE }}
          role-duration-seconds: 3600
          role-session-name: GitHubActions

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@c962da2960ed15f492addc26fffa274485265950 # v2.0.2
        with:
          registries: 311462405659

      - name: Snyk Scan
        id: snyk_scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@SP-3628
        with:
          SNYK_TEST_IMAGE: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/integrations/lpa-uid-create-case-lambda:latest
          SNYK_TOKEN: ${{ secrets.snyk_token }}

      - name: Upload Snyk scan results to GitHub Security tab
        id: snyk_upload_sarif
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        if: always()
        with:
          category: "Docker"
          sarif_file: "test-results/snyk.sarif"

      - name: Save Images
        run: |
          mkdir -p /tmp/images
          docker save -o /tmp/images/lambda-create-case.tar 311462405659.dkr.ecr.eu-west-1.amazonaws.com/integrations/lpa-uid-create-case-lambda:latest
