name: "Deploy to Environment"

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      apply:
        description: "Should the terraform changes be applied"
        default: false
        required: false
        type: boolean

      oidc_role:
        description: "The OIDC role to assume for AWS access"
        required: true
        type: string

      default_role:
        description: "The default CI role to assume"
        required: true
        type: string

      management_role:
        description: "The management CI role to assume"
        required: true
        type: string

      shared_role:
        description: "The shared CI role to assume"
        required: true
        type: string

      workspace_name:
        description: "The terraform workspace to target for environment actions"
        required: true
        type: string

      version_tag:
        description: "The docker image tag to deploy in the environment"
        required: true
        type: string

    secrets:
      github_access_token:
        description: "Github Token"
        required: true
      ssh_private_key_allow_list_repository:
        description: "SSH Deploy Key"
        required: true

jobs:
  terraform_environment_workflow:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ inputs.workspace_name }}
      TF_VAR_app_version: ${{ inputs.version_tag }}
      TF_VAR_default_role: ${{ inputs.default_role }}
      TF_VAR_management_role: ${{ inputs.management_role }}
      TF_VAR_shared_role: ${{ inputs.shared_role }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: "0"

      - uses: unfor19/install-aws-cli-action@f5b46b7f32cf5e7ebd652656c5036bf83dd1e60c # v1

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.12.2
          terraform_wrapper: false

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.oidc_role }}
          role-duration-seconds: 3600
          role-session-name: OPGDataLpaUIDGithubAction

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.ssh_private_key_allow_list_repository }}

      - name: Terraform Init
        working-directory: ./terraform/environment
        run: terraform init -input=false

      - name: Terraform Plan
        id: terraform_plan
        working-directory: ./terraform/environment
        run: |
          terraform workspace show
          echo "plan_summary=$(terraform plan -no-color -lock-timeout=300s -input=false -parallelism=30 | grep -ioE 'Plan: [[:digit:]]+ to add, [[:digit:]]+ to change, [[:digit:]]+ to destroy|No changes. Your infrastructure matches the configuration.')" >> $GITHUB_OUTPUT
          terraform plan -lock-timeout=300s -input=false -out=${{ env.TF_WORKSPACE }}.plan -parallelism=30


      - name: Terraform Apply
        if: inputs.apply == true
        working-directory: ./terraform/environment
        run: terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30 ${{ env.TF_WORKSPACE }}.plan
