name: Run Gosec
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Run Gosec Security Scanner
        uses: securego/gosec@deb54465fea23d19a77f037e11e6589021f8501d # v2.29.0
        with:
          args: ./lambda/create-case
