name: Spectral

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: docs/openapi/openapi.yaml
