name: Test & Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      snyk_token: ${{ secrets.SNYK_OPG_ORG_TOKEN }}

  test-terraform:
    name: Test Terraform
    uses: ./.github/workflows/_test-terraform.yml
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      snyk_token: ${{ secrets.SNYK_OPG_ORG_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: "0"
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 'stable'
      - name: Run unit tests
        run: make test

  integration-test:
    name: Integration test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Image cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/images
          key: ${{ runner.os }}-images-${{ github.run_id }}-${{ github.run_number }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.12.2
          terraform_wrapper: false
      - name: Restore Image
        run: docker load -i /tmp/images/lambda-create-case.tar
      - run: make up test-api

  push:
    name: Push images
    needs: [test, integration-test, test-terraform]
    uses: ./.github/workflows/_push.yml
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-development:
    name: Deploy to Development
    needs: [push]
    uses: ./.github/workflows/_deploy.yml
    with:
      workspace_name: development
      apply: true
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      shared_role: ${{ vars.SHARED_DEVELOPMENT_ROLE }}
      version_tag: ${{ needs.push.outputs.tag }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  deploy-preproduction:
    name: Deploy to Preproduction
    needs: [push, deploy-development]
    uses: ./.github/workflows/_deploy.yml
    with:
      workspace_name: preproduction
      apply: true
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.PREPRODUCTION_MAIN_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      shared_role: ${{ vars.SHARED_DEVELOPMENT_ROLE }}
      version_tag: ${{ needs.push.outputs.tag }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  deploy-demo:
    name: Deploy to Demo
    needs: [push, deploy-preproduction]
    uses: ./.github/workflows/_deploy.yml
    with:
      workspace_name: demo
      apply: true
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      shared_role: ${{ vars.SHARED_DEVELOPMENT_ROLE }}
      version_tag: ${{ needs.push.outputs.tag }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
