name: Test & Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yml
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      snyk_token: ${{ secrets.SNYK_OPG_ORG_TOKEN }}

  test-terraform:
    name: Test Terraform
    uses: ./.github/workflows/_test-terraform.yml
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      snyk_token: ${{ secrets.SNYK_OPG_ORG_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: "0"
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 'stable'
      - name: Run unit tests
        run: make test

  integration-test:
    name: Integration test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Image cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/images
          key: ${{ runner.os }}-images-${{ github.run_id }}-${{ github.run_number }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.12.2
          terraform_wrapper: false
      - name: Restore Image
        run: docker load -i /tmp/images/lambda-create-case.tar
      - run: make up test-api

  push:
    name: Push images
    needs: [test, integration-test, test-terraform]
    uses: ./.github/workflows/_push.yml
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  plan-environment:
    strategy:
      matrix:
        include:
          - workspace_name: development
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.DEVELOPMENT_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            shared_role: ${{ vars.SHARED_DEVELOPMENT_ROLE }}
          - workspace_name: preproduction
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PREPRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
            shared_role: ${{ vars.SHARED_DEVELOPMENT_ROLE }}
    name: "Terraform Plan Environment: ${{ matrix.workspace_name }}"
    needs:
      - push
    uses: ./.github/workflows/_deploy.yml
    with:
      apply: false
      workspace_name: ${{ matrix.workspace_name }}
      oidc_role: ${{ matrix.oidc_role }}
      default_role: ${{ matrix.default_role }}
      management_role: ${{ matrix.management_role }}
      shared_role: ${{ matrix.shared_role }}
      version_tag: ${{ needs.push.outputs.tag }}
    secrets:
      ssh_private_key_allow_list_repository: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
